site_name: Diataxis Material for MkDocs Guide
site_url: https://khde.github.io/diataxis-material-mkdocs-guide
repo_url: https://github.com/khde/diataxis-material-mkdocs-guide
edit_uri: https://github.com/khde/diataxis-material-mkdocs-guide/tree/master/docs
site_description: Diátaxis-based documentation for Material for MkDocs
docs_dir: docs

nav:
  - Home: index.md
  - Tutorials:
      - tutorials/index.md
      - Getting started: tutorials/getting-started.md
      - First site: tutorials/first-site.md
      - Adding pages and navigation: tutorials/adding-pages-and-navigation.md
      - Configuring your site: tutorials/configuring-your-site.md
      - Using Markdown extensions: tutorials/markdown-extensions.md
  - How-to Guides:
      - how-to/index.md
      - Deploy to GitHub Pages: how-to/deploy-github-pages.md
      - Generate PDF: how-to/generate-pdf.md
      - Show editing information: how-to/show-edit-information.md
  - Reference:
      - reference/index.md
      - Commands: reference/commands.md
      - YAML Configuration: reference/yaml-configuration.md
  - Explanation:
      - explanation/index.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-page-variant
  
  features:
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light mode
  
  font:
    text: Inter
    code: Google Sans Code

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  generator: false